[package]
name = "werbolg-lang-rusty"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chumsky = { version = "0.9", features = [] }
logos = { version = "0.13" }
werbolg-lang-common = { path = "../werbolg-lang-common" }
werbolg-core = { path = "../werbolg-core" }
