[package]
name = "werbolg-lang-common"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
werbolg-core = { path = "../werbolg-core" }
#unicode-width = "0.4"
